branches:
  only:
  - master

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"

language: r
sudo: required
cache: packages
warnings_are_errors: true
r_check_args: ''

r:
  - release
  - devel

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

bioc_required: true

r_packages:
  - devtools
  - covr

r_github_packages:
  - jimhester/covr
  - nhejazi/methyvimData

bioc_packages:
  - BiocStyle
  - BiocCheck
  - BiocParallel
  - BiocGenerics
  - SummarizedExperiment
  - GenomeInfoDb
  - bumphunter
  - IRanges
  - limma
  - minfi
  - minfiData

## coverage
after_success:
  - travis_wait Rscript -e "covr::codecov(line_exclusions = list('R/plots.R', 'R/utils.R'))"
  - R CMD BiocCheck .

notifications:
  email:
    on_success: change
    on_failure: change

