---
title: "Targeted Learning of Differential Methylation from Exposures"
author: "Nima Hejazi"
date: "`r Sys.Date()`"
output:
  BiocStyle::html_document2
bibliography: refs.bib
vignette: >
  %\VignetteIndexEntry{Targeted Learning of Differential Methylation from Exposures}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introduction

...

---

## Preliminaries

First, we'll load the `methyvim` package and the example data contained in the
`methyvimData` package that accompanies it:

```{r load_pkgs}
library(methyvim)
suppressMessages(library(minfi))
suppressMessages(library(SummarizedExperiment))
suppressMessages(library(tmle))
```

```{r prelims}
#options(future.globals.maxSize = 1e12)
set.seed(479253)
```

Now, let's load the data set:

```{r}
library(methyvimData)
data(grsExample)
grsExample
```

---

## Quantifying the Effect of an Exposure on DNA Methylation

### The Average Treatment Effect as Variable Importance Measure

...

```{r methyvim-ate}
methyvim_out <- methyvim(data_grs = grsExample, sites_comp = 10,
                         var_int = 1, vim = "ATE", type = "Mval",
                         filter = "limma", filter_cutoff = 0.05,
                         window_bp = 1e3, corr_max = 0.80, obs_per_covar = 20,
                         parallel = F, future_param = NULL, bppar_type = NULL,
                         return_ic = FALSE, shrink_ic = FALSE,
                         tmle_type = "super_learning"
                        )
```

...

---

## Session Information

```{r sessionInfo, echo=FALSE}
sessionInfo()
```

---

## References

