#' Check Function Inputs
#'
#' Check the input values of function parameters for errors.
#'
#' @param data ...
#' @param var ...
#' @param filter_cutoff ...
#' @param window ...
#' @param corr ...
#' @param obs_per_covar ...
#' @param parallel ...
#' @param future ...
#' @param bppar ...
#' @param tmle_type ...
#' @param tmle_args ...
#'
#' @return Options to be passed to various \code{tmle_*} functions.
#'
check_inputs <- function(data, var, filter_cutoff, window, corr, obs_per_covar,
                         parallel, future, bppar, tmle_type, tmle_args) {

  # NOTE: make sure to check combinations of the variable of interest and the
  # stated parameter of interest (i.e., VIM). In particular, we will use the
  # following heuristic to decide between NPVI and ATE: if the variable of
  # interest is discretized, use the ATE, with the Y = CpG site i, A = treatment
  # (discretized), and W = neighboring uncorrelated sites; if the variable of
  # interest is continuous, use NPVI. We don't actually need to impose the
  # heuristic, but use it to check that the user has specified the ATE vs. NPVI
  # parameters correctly.

  #  TODO: all other arguments in catch_inputs
  message("Checking function inputs has not yet been implemented.")
}
