#' S3 constructor for class methadapt
#'
#' @param call merely passed in from \code{match.call(expand.dots = TRUE)}.
#' @param tmleOut \code{data.frame} containing the output generated by use of
#'        \code{methytmle}
#'
#' @return S3 object of class "methadapt" for DNA methylation analysis based on
#'         targeted minimum loss-based estimation.
#'
#' @export biotmle
#'
methadapt <- function(call = NULL,
                      tmleOut = NULL) {
  # ============================================================================
  # generic skeleton for S3 class
  # ============================================================================
  out <- structure(list(call,
                        tmleOut
                       ),
                   class = "methadapt")

  names(out) <- c("call", "tmleOut")
  return(out)
}
